apiVersion: v1
kind: Pod
metadata:
  name: download-pod
  namespace: ftschirpke
spec:
  containers:
  - name: download
    image: friedricht/wow-download
    command:
      - /bin/sh
      - "-c"
      - "sleep infinity"
    workingDir: /input/workflow-inputs
    volumeMounts:
      - mountPath: /input
        name: input
    securityContext:
      runAsUser: 0
  volumes:
  - name: input
    persistentVolumeClaim:
      claimName: ceph-data
  securityContext:
    runAsUser: 0
